python3 train/train_rnn.py \
  --data_dir /media/fanis/Intenso/wm18/latent64_vizdoom_1_32_2.5k \
  --load_pretrained None 
  --desc '1. seq150, dropout 0.2, train from scratch ' \
  --checkpoint_interval 10 \
  --seed 99 \
  --epochs 100 \
  --batch_size 128 \
  --sequence_length 150 \
  --val_split 0.1 \
  --latent_dim 64 \
  --action_dim 1 \
  --hidden_size 512 \
  --n_layers 1 \
  --n_gaussians 5 \
  --lr 1e-3 \
  --done_loss_weight 40.0 \
  --patience_lr 5 \
  --patience_epochs 25 \
  --dropout 0.2 \
